project_id = "uulsigivyqoyakgflnrj"

[functions.generate-image]
verify_jwt = false

[functions.generate-post]
verify_jwt = false

[functions.generate-sample-posts]
verify_jwt = false

[functions.run-agent]
verify_jwt = false

[functions.extension-auth]
verify_jwt = false

[functions.pending-posts]
verify_jwt = false

[functions.post-complete]
verify_jwt = false

[functions.extension-analytics]
verify_jwt = false

[functions.analytics-latest]
verify_jwt = false
