project_id = "uulsigivyqoyakgflnrj"

[functions.linkedin-oauth-init]
verify_jwt = false

[functions.linkedin-oauth-callback]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-post]
verify_jwt = false

[functions.generate-sample-posts]
verify_jwt = false

[functions.post-to-linkedin]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.run-agent]
verify_jwt = false
